language: python
python:
- 2.7
- 3.5
env:
- TOXENV=django111
matrix:
  include:
  - python: 3.5
    env: TOXENV=quality
  - python: 3.5
    env: TOXENV=docs
  - python: 3.5
    env: TOXENV=django20
cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
